path: /data/mreza/CaveSegmentation/data
train: images/train 
val: images/val  

nc: 13
names: ['class1', 'class2','class3','class4','class5','class6','class7','class8','class9','class10','class11', class12, class13]